version: "3.9"

services:
  kms-service:
    build: ./kms-service
    container_name: kms-service
    ports:
      - "8000:8000"
    environment:
      - MASTER_KEY_PASSPHRASE=dev-master-pass
      - KMS_DATABASE_URL=postgresql+psycopg2://kms:kms@kms-db:5432/kms_poc_kms
    networks:
      - backend
    depends_on:
      kms-db:
        condition: service_healthy

  data-service:
    build: ./data-service
    container_name: data-service
    ports:
      - "8001:8001"
    environment:
      - KMS_BASE_URL=http://kms-service:8000
      - DATABASE_URL=postgresql+psycopg2://kms:kms@data-service-db:5432/kms_poc_data
    depends_on:
      kms-service:
        condition: service_started
      data-service-db:
        condition: service_healthy
    networks:
      - backend

  data-service-db:
    image: postgres:16
    container_name: data-service-db
    environment:
      - POSTGRES_USER=kms
      - POSTGRES_PASSWORD=kms
      - POSTGRES_DB=kms_poc_data
    ports:
      - "5432:5432"
    volumes:
      - db_data_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kms -d kms_poc_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  kms-db:
    image: postgres:16
    container_name: kms-kms-db
    environment:
      - POSTGRES_USER=kms
      - POSTGRES_PASSWORD=kms
      - POSTGRES_DB=kms_poc_kms
    ports:
      - "55432:5432"
    volumes:
      - db_kms_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kms -d kms_poc_kms"]
      interval: 5s
      timeout: 5s
      retries: 5

  ui:
    build: ./ui
    container_name: kms-ui
    ports:
      - "5173:80"
    depends_on:
      - kms-service
      - data-service
    networks:
      - backend

networks:
  backend:

volumes:
  db_data_data:
  db_kms_data:
