worker_processes  1;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  upstream ui_upstream {
    server kms-ui:80;
  }

  upstream kms_upstream {
    server kms-service:8000;
  }

  upstream data_upstream {
    server data-service:8001;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://ui_upstream;
    }

    location /kms/ {
      proxy_pass http://kms_upstream/;
    }

    location /data/ {
      proxy_pass http://data_upstream/;
    }
  }
}
